### ISSUE TITLE
Support for othter font formats

### ISSUE THREAD

**Issue by alexanderadam** [Stxr/iconfont-preview-extension#2]
For instance `eot` or `woff`.

Thank you so much for this extension. It is great! :pray:

**Comment by Stxr** [comment]
Thank you for your advice,it's in the plan.

**Comment by Stxr** [comment]
> For instance `eot` or `woff`.
> 
> Thank you so much for this extension. It is great! 🙏

Thank you for your advice,it's in the plan.

**Comment by Stxr** [comment]
support eot, woff,woff2,otf at 0.0.5.
